name: Docker Build Check

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR targeting the main branch
    types: 
      - opened      # Trigger when a PR is opened
      - reopened    # Trigger when a PR is reopened
      - synchronize # Trigger when a PR is updated with new commits

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          echo "Simulating failure"
          exit 1  # Force failure
